begin;
do $$
#variable_conflict use_variable
declare admin uuid;scorer uuid;scorer2 uuid;outsider uuid;s1 uuid;s2 uuid;mid uuid;slot uuid;cid uuid;roundid uuid;div uuid;token1 uuid:=gen_random_uuid();token2 uuid:=gen_random_uuid();cfg jsonb;ctx jsonb;result jsonb;counts jsonb;rejected boolean;backup_id uuid;
begin
  insert into app_accounts(club_code,username,display_name,role,is_admin)values('gast','scoring-admin-'||gen_random_uuid(),'Scoring Organizer Test','trainer',true)returning id into admin;
  insert into app_accounts(club_code,username,display_name,role)values('svbb','lid.'||replace(gen_random_uuid()::text,'-',''),'Scoring Visitor Test','schutter')returning id into scorer;
  insert into app_accounts(club_code,username,display_name,role)values('gast','lid.'||replace(gen_random_uuid()::text,'-',''),'Scoring Second Test','schutter')returning id into scorer2;
  insert into app_accounts(club_code,username,display_name,role,is_admin)values('svbb','scoring-admin-'||gen_random_uuid(),'Scoring Other Organizer','trainer',true)returning id into outsider;
  insert into platform_users(id,auth_provider_id)select id,'test:'||id from app_accounts where id in(admin,scorer,scorer2,outsider);
  insert into shooters(display_name,linked_user_id)values('Scoring Visitor Test',scorer)returning id into s1;
  insert into shooters(display_name,linked_user_id)values('Scoring Second Test',scorer2)returning id into s2;
  insert into memberships(shooter_id,club_id)select s1,id from clubs where code='svbb';
  insert into memberships(shooter_id,club_id)select s2,id from clubs where code='gast';
  select id into cid from clubs where code='gast';
  insert into epp_matches(club_id,organizer,match_date,offered_disciplines)values('gast','Scoring Integration Test','2031-11-14',array['pistool','optiek'])returning id into mid;
  cfg:='{"first":"09:00","last":"10:00","duration":30,"changeover":0,"capacity":10,"gap":0,"opens":"2020-01-01T00:00:00Z","closes":"2031-11-13T00:00:00Z","published":true,"breaks":[],"overrides":[]}';
  perform epp_planner_configure(admin,mid,cfg,0);
  select id into slot from epp_match_slots where match_id=mid order by starts_at limit 1;
  perform epp_planner_book(scorer,mid,s1,jsonb_build_array(jsonb_build_object('discipline','pistool','slotId',slot)),0);
  perform epp_planner_book(scorer2,mid,s2,jsonb_build_array(jsonb_build_object('discipline','pistool','slotId',slot)),0);
  ctx:=epp_scoring_prepare(admin,mid);roundid:=(ctx->>'roundId')::uuid;
  rejected:=false;begin update epp_matches set organizer='Renamed test'where id=mid;exception when others then if sqlerrm='wedstrijd_invoer_vast'then rejected:=true;else raise;end if;end;assert rejected,'identity bypass';
  rejected:=false;begin perform epp_scoring_prepare(scorer,mid);exception when others then if sqlerrm='geen_wedstrijdrechten'then rejected:=true;else raise;end if;end;assert rejected,'unassigned';
  rejected:=false;begin perform epp_scoring_control(outsider,mid,'scorer',scorer,true,1);exception when others then if sqlerrm='geen_beheerrechten'then rejected:=true;else raise;end if;end;assert rejected,'other organizer';
  perform epp_scoring_control(admin,mid,'scorer',scorer,true,1);
  perform epp_scoring_control(admin,mid,'scorer',scorer2,true,2);
  perform epp_scoring_prepare(scorer,mid);
  perform epp_scoring_lease(scorer,mid,s1,'pistool',token1);
  rejected:=false;begin perform epp_scoring_lease(scorer2,mid,s1,'pistool',token2);exception when others then if sqlerrm='schutter_in_bewerking'then rejected:=true;else raise;end if;end;assert rejected,'same participant collision';
  rejected:=false;begin perform epp_scoring_lease(scorer,mid,s1,'pistool',token2);exception when others then if sqlerrm='schutter_in_bewerking'then rejected:=true;else raise;end if;end;assert rejected,'two tabs collision';
  perform epp_scoring_lease(scorer2,mid,s2,'pistool',token2);
  rejected:=false;begin perform epp_scoring_control(admin,mid,'close',null,true,3);exception when others then if sqlerrm='invoer_nog_actief'then rejected:=true;else raise;end if;end;assert rejected,'closing active input';
  counts:='{"hits5":50,"hits4":0,"hits3":0,"hits2":0,"misses":0,"penaltyPoints":0,"rapid":{"hits5":10,"hits4":0,"hits3":0,"hits2":0,"misses":0},"rapidTimeMs":12400,"totalTimeMs":293000,"penaltyTimeMs":0}';
  result:=epp_scoring_submit(scorer,mid,s1,'pistool',token1,counts,'scoring-test-'||mid,0,'');
  assert result->>'represented_club_id'=(select id::text from clubs where code='svbb'),'home club preserved';
  assert not exists(select 1 from memberships where shooter_id=s1 and club_id=cid),'no false membership';
  assert not exists(select 1 from epp_score_leases where match_id=mid and shooter_id=s1),'lease released';
  assert epp_scoring_submit(scorer,mid,s1,'pistool',token1,counts,'scoring-test-'||mid,0,'')=result,'retry idempotent';
  perform epp_scoring_lease(scorer,mid,s1,'pistool',token1);
  rejected:=false;begin perform epp_scoring_submit(scorer,mid,s1,'pistool',token1,counts,'scoring-stale-'||mid,0,'Correctie');exception when others then if sqlerrm='score_conflict'then rejected:=true;else raise;end if;end;assert rejected,'stale revision';
  rejected:=false;begin perform epp_scoring_submit(scorer,mid,s1,'pistool',token1,counts,'scoring-reason-'||mid,1,'');exception when others then if sqlerrm='correctiereden_verplicht'then rejected:=true;else raise;end if;end;assert rejected,'reason required';
  perform epp_scoring_submit(scorer,mid,s1,'pistool',token1,counts,'scoring-correct-'||mid,1,'Kaart opnieuw geteld');
  assert exists(select 1 from result_audit where actor_id=scorer and reason='Kaart opnieuw geteld'),'correction audit';
  perform epp_scoring_control(admin,mid,'scorer',scorer2,false,3);
  rejected:=false;begin perform epp_scoring_lease(scorer2,mid,s2,'pistool',token2);exception when others then if sqlerrm='geen_wedstrijdrechten'then rejected:=true;else raise;end if;end;assert rejected,'revoked';
  perform epp_scoring_control(admin,mid,'close',null,true,4);
  rejected:=false;begin perform epp_scoring_submit(scorer,mid,s1,'pistool',token1,counts,'scoring-closed-'||mid,2,'Correctie');exception when others then if sqlerrm='uitslag_definitief'then rejected:=true;else raise;end if;end;assert rejected,'closed';
  assert not exists(select 1 from app_accounts where id=scorer and (role='trainer' or is_admin)),'no club privileges';
  backup_id:=epp_capture_backup();
  assert (select snapshot?'epp_scoring_matches' and snapshot?'epp_match_scorers' and snapshot?'epp_scoring_audit' from platform_backups where id=backup_id),'backup scoring data';
end $$;
rollback;
