begin;
do $$
#variable_conflict use_variable
declare admin_id uuid;other_admin uuid;member_id uuid;member2 uuid;head uuid;s1 uuid;s2 uuid;match_id uuid;slot1 uuid;slot2 uuid;cfg jsonb;result jsonb;rejected boolean;backup_id uuid;cid uuid;ev uuid;rnd uuid;div uuid;season uuid;rule uuid;legacy_signup uuid;
begin
  insert into app_accounts(club_code,username,display_name,role,is_admin) values('gast','planner-test-'||gen_random_uuid(),'Planner Beheer','trainer',true) returning id into admin_id;
  insert into app_accounts(club_code,username,display_name,role,is_admin) values('svbb','planner-test-'||gen_random_uuid(),'Andere Beheer','trainer',true) returning id into other_admin;
  insert into app_accounts(club_code,username,display_name,role) values('gast','planner-test-'||gen_random_uuid(),'Test Schutter Een','schutter') returning id into member_id;
  insert into app_accounts(club_code,username,display_name,role) values('svbb','planner-test-'||gen_random_uuid(),'Test Schutter Twee','schutter') returning id into member2;
  insert into platform_users(id,auth_provider_id) values(member_id,'test:'||member_id),(member2,'test:'||member2),(admin_id,'test:'||admin_id);
  insert into shooters(display_name,linked_user_id)values('Planner Test Een',member_id) returning id into s1;
  insert into shooters(display_name,linked_user_id)values('Planner Test Twee',member2) returning id into s2;
  insert into epp_matches(club_id,organizer,match_date,offered_disciplines)values('gast','Planner Test','2030-11-14',array['pistool','optiek']) returning id into match_id;
  cfg:=jsonb_build_object('first','09:00','last','11:00','duration',30,'changeover',0,'capacity',1,'gap',0,'opens','2020-01-01T00:00:00Z','closes','2030-11-13T00:00:00Z','published',true,'breaks',jsonb_build_array(jsonb_build_object('start','10:00','end','10:30')),'overrides',jsonb_build_array(jsonb_build_object('start','11:00','capacity',2)));
  insert into epp_signups(match_id,shooter_id,shooter_name)values(match_id,s1,'Planner Test Een') returning id into legacy_signup;
  insert into epp_signup_disciplines(signup_id,discipline,time_block)values(legacy_signup,'pistool','ochtend');
  rejected:=false;begin perform epp_planner_configure(admin_id,match_id,cfg,0);exception when others then if sqlerrm='bestaande_inschrijvingen_eerst_plannen' then rejected:=true;else raise;end if;end;assert rejected,'legacy publication';
  result:=epp_planner_configure(admin_id,match_id,cfg||'{"published":false}',0);
  assert exists(select 1 from epp_signup_disciplines where signup_id=legacy_signup and slot_id is null),'legacy preserved';
  assert (select count(*) from epp_match_slots where epp_match_slots.match_id=match_id)=4;
  select id into slot1 from epp_match_slots where epp_match_slots.match_id=match_id order by starts_at limit 1;
  select id into slot2 from epp_match_slots where epp_match_slots.match_id=match_id order by starts_at offset 1 limit 1;
  perform epp_planner_book(admin_id,match_id,s1,jsonb_build_array(jsonb_build_object('discipline','pistool','slotId',slot1)),0,'Bestaande inschrijving inplannen');
  result:=epp_planner_configure(admin_id,match_id,cfg,1);
  perform epp_planner_book(member_id,match_id,s1,jsonb_build_array(jsonb_build_object('discipline','pistool','slotId',slot1)),0);
  rejected:=false;begin perform epp_planner_book(member2,match_id,s2,jsonb_build_array(jsonb_build_object('discipline','pistool','slotId',slot1)),0);exception when others then if sqlerrm='tijdslot_vol' then rejected:=true;else raise;end if;end;assert rejected,'capacity';
  rejected:=false;begin perform epp_planner_book(member2,match_id,s1,'[]',1);exception when others then if sqlerrm='alleen_eigen_inschrijving' then rejected:=true;else raise;end if;end;assert rejected,'ownership';
  rejected:=false;begin perform epp_planner_book(member_id,match_id,s1,jsonb_build_array(jsonb_build_object('discipline','pistool','slotId',slot1),jsonb_build_object('discipline','optiek','slotId',slot1)),1);exception when others then if sqlerrm='overlappende_boeking' then rejected:=true;else raise;end if;end;assert rejected,'overlap';
  rejected:=false;begin perform epp_planner_configure(other_admin,match_id,cfg,1);exception when others then if sqlerrm='wedstrijd_niet_gevonden' then rejected:=true;else raise;end if;end;assert rejected,'other club';
  rejected:=false;begin perform epp_planner_configure(admin_id,match_id,cfg||'{"duration":20}',2);exception when others then if sqlerrm='geboekte_tijdsloten_behouden' then rejected:=true;else raise;end if;end;assert rejected,'booked schedule';
  rejected:=false;begin perform epp_signup_save(member_id,'gast',match_id,s1,'[]',true);exception when others then if sqlerrm='gebruik_wedstrijdplanner' then rejected:=true;else raise;end if;end;assert rejected,'legacy bypass';
  perform epp_planner_book(member_id,match_id,s1,jsonb_build_array(jsonb_build_object('discipline','pistool','slotId',slot1)),0);
  perform epp_planner_book(admin_id,match_id,s1,jsonb_build_array(jsonb_build_object('discipline','pistool','slotId',slot2)),1,'Verzoek schutter');
  rejected:=false;begin perform epp_planner_book(member_id,match_id,s1,'[]',1);exception when others then if sqlerrm='boeking_conflict' then rejected:=true;else raise;end if;end;assert rejected,'revision';
  perform epp_planner_book(member_id,match_id,s1,'[]',2);
  perform epp_planner_book(member2,match_id,s2,jsonb_build_array(jsonb_build_object('discipline','optiek','slotId',slot1)),0);
  result:=epp_match_participants(admin_id,match_id,'optiek');assert jsonb_array_length(result->'shooters')=1;
  select id into cid from clubs where code='gast';
  insert into divisions(naam) values('Open') on conflict(naam) do nothing;
  select id into div from divisions where naam='Open';
  insert into seasons(naam,start_date,end_date) values('Planner test '||gen_random_uuid(),current_date,current_date+365) returning id into season;
  insert into rule_profiles(version) values('Planner test '||gen_random_uuid()) returning id into rule;
  insert into events(organizer_club_id,season_id,naam,type,rule_profile_id,registration_match_id,ranking_eligible) values(cid,season,'Planner score test','wedstrijd',rule,match_id,true) returning id into ev;
  insert into rounds(event_id,label) values(ev,'Wedstrijdscore') returning id into rnd;
  result:=epp_confirm_timed_result(admin_id,cid,rnd,s2,div,'{"hits5":50,"hits4":0,"hits3":0,"hits2":0,"misses":0,"penaltyPoints":0,"rapid":{"hits5":10,"hits4":0,"hits3":0,"hits2":0,"misses":0},"rapidTimeMs":12400,"totalTimeMs":293000,"penaltyTimeMs":0}', 'planner-score-'||match_id,0,'');
  assert result->>'represented_club_id'=(select id::text from clubs where code='svbb'),'visitor keeps association';
  assert not exists(select 1 from memberships where shooter_id=s2 and club_id=cid),'no fake membership';
  assert exists(select 1 from epp_planner_audit where actor_id=admin_id and action='book' and reason='Verzoek schutter');
  insert into app_accounts(club_code,username,display_name,role,is_admin,is_platform_admin,must_change_password) values('eppnationaal','head-test-'||gen_random_uuid(),'Test Hoofdbeheer','trainer',true,true,true) returning id into head;
  rejected:=false;begin perform epp_set_club_admin(head,member_id,true);exception when others then if sqlerrm='geen_hoofdbeheerrechten' then rejected:=true;else raise;end if;end;assert rejected,'first password';
  update app_accounts set must_change_password=false where id=head;
  perform epp_set_club_admin(head,member_id,true);
  assert exists(select 1 from app_accounts where id=member_id and role='trainer' and is_admin);
  assert exists(select 1 from shooters where id=s1 and linked_user_id=member_id);
  rejected:=false;begin perform epp_set_club_admin(admin_id,member2,true);exception when others then if sqlerrm='geen_hoofdbeheerrechten' then rejected:=true;else raise;end if;end;assert rejected,'head only';
  perform epp_set_club_admin(head,member_id,false);
  assert exists(select 1 from epp_access_audit where target_id=member_id);
  backup_id:=epp_capture_backup();
  assert (select snapshot?'epp_match_slots' and snapshot?'epp_access_audit' from platform_backups where id=backup_id);
end $$;
rollback;
